server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://116.63.204.44:3306/lxs-blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: HuaWei.25650
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    allow-circular-references: true
  redis:
    host: 116.63.204.44
    port: 6379
    lettuce:
      pool:
        max-active: 8   #最大连接数
        max-idle: 8     #最大空闲连接数
        min-idle: 0     #最小空闲连接数
        max-wait: 100ms #等待连接时间
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto



obs:
  endPoint: https://obs.cn-east-3.myhuaweicloud.com
  ak: SDMV8KQGOYHZWXSNTDPT
  sk: 2wFyORm1kqIS4yQeRfxFTof59ta25ChdOluhPE9C
